# Generated by Django 4.1.4 on 2023-01-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_Name', models.CharField(max_length=100)),
                ('Dept_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Location', models.CharField(max_length=100)),
                ('Dept_No', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aishu.employee')),
            ],
        ),
    ]
